//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id_comment { get; set; }
        public string content_cmt { get; set; }
        public int id_account { get; set; }
        public int idea { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    
        public virtual account account { get; set; }
    }
}
