//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reaction
    {
        public int reaction_id { get; set; }
        public int id_idea { get; set; }
        public int id_account { get; set; }
    
        public virtual account account { get; set; }
        public virtual idea idea { get; set; }
    }
}
